name: Deployment

on:
  workflow_dispatch:

jobs:
  train:
    environment: PROD
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: create a real-time endpoint
      run: az ml endpoint create --file ./src/endpoint.yml -g rg-distillation-raf -w ws-distillation-raf
    - name: deploy model to endpoint
      run: az ml online-deployment create --file ./src/deployment.yml -g rg-distillation-raf -w ws-distillation-raf


