name: dev-prod-run

on: 
  push:
    branches:    
      - main

jobs:
  job1:
    name: experiment
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - name: check out repo
      uses: actions/checkout@main
    - name: install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: run ML job
      run: az ml job create -f ./src/job_dev.yml -g rg-distillation-raf -w ws-distillation-raf
  job2:
    name: production
    runs-on: ubuntu-latest
    environment: PROD
    needs: job1
    steps:
    - name: check out repo
      uses: actions/checkout@main
    - name: install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: run ML job
      run: az ml job create -f ./src/job_prod.yml -g rg-distillation-raf -w ws-distillation-raf
  