name: Placeholder

on: 
  pull_request:

jobs:
  job1:
    name: Placeholder
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"